"""Turn data/content/overrides/custom_content.json into a header the runtime can read.

The ranges that say which custom items carry a stat budget live in that file, and until now only the
census generator read them - which needs a database, so the runtime had nothing and fell back to
preserving every custom item. This writes them out as a table instead. It needs no database, so the
header can be regenerated whenever the file changes.
"""
import io
import json
import pathlib

POLICIES = {"STANDARD": 0, "TIER_ALIGNED": 1, "EXEMPT_PRESERVE": 2, "REVIEW_SPECIAL": 3}

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = ROOT / "data/content/overrides/custom_content.json"
TARGET = ROOT / "include/GeneratedCustomRanges.h"


def main():
    rules = json.loads(SOURCE.read_text(encoding="utf-8"))
    rows = []
    for rule in sorted(rules, key=lambda r: r["entry_range"][0]):
        low, high = rule["entry_range"]
        policy = POLICIES[rule["scaling_policy"]]
        rows.append(f'    GeneratedCustomRange{{ {low}u, {high}u, {policy} }},'
                    f'   // {rule["category"]}')

    out = [
        "/*",
        " * CoA Universal Content Scaling",
        " * GeneratedCustomRanges: which custom item ranges carry a stat budget.",
        " * Automatically generated by tools/content_census/generate_custom_ranges.py",
        " * from data/content/overrides/custom_content.json. Do not edit by hand.",
        " */",
        "",
        "#ifndef GENERATED_CUSTOM_RANGES_H",
        "#define GENERATED_CUSTOM_RANGES_H",
        "",
        '#include "Define.h"',
        "#include <array>",
        "",
        "struct GeneratedCustomRange",
        "{",
        "    uint32 first;",
        "    uint32 last;",
        "    uint8 policy;   // 0 STANDARD, 1 TIER_ALIGNED, 2 PRESERVE, 3 REVIEW_SPECIAL",
        "};",
        "",
        f"inline constexpr std::array<GeneratedCustomRange, {len(rows)}> sGeneratedCustomRanges =",
        "{{",
        *rows,
        "}};",
        "",
        "inline GeneratedCustomRange const* FindGeneratedCustomRange(uint32 itemId)",
        "{",
        "    for (GeneratedCustomRange const& range : sGeneratedCustomRanges)",
        "        if (itemId >= range.first && itemId <= range.last)",
        "            return &range;",
        "",
        "    return nullptr;",
        "}",
        "",
        "#endif // GENERATED_CUSTOM_RANGES_H",
        "",
    ]
    io.open(TARGET, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"wrote {TARGET.relative_to(ROOT)} with {len(rows)} ranges")


if __name__ == "__main__":
    main()
