/*
 * CoA Universal Content Scaling
 * GeneratedCustomRanges: which custom item ranges carry a stat budget.
 * Automatically generated by tools/content_census/generate_custom_ranges.py
 * from data/content/overrides/custom_content.json. Do not edit by hand.
 */

#ifndef GENERATED_CUSTOM_RANGES_H
#define GENERATED_CUSTOM_RANGES_H

#include "Define.h"
#include <array>

struct GeneratedCustomRange
{
    uint32 first;
    uint32 last;
    uint8 policy;   // 0 STANDARD, 1 TIER_ALIGNED, 2 PRESERVE, 3 REVIEW_SPECIAL
};

inline constexpr std::array<GeneratedCustomRange, 3> sGeneratedCustomRanges =
{{
    GeneratedCustomRange{ 100000u, 200000u, 2 },   // CUSTOM_COSMETIC
    GeneratedCustomRange{ 200001u, 350000u, 2 },   // CUSTOM_CLASS_ITEM
    GeneratedCustomRange{ 350001u, 4294967295u, 1 },   // CUSTOM_GAMEPLAY
}};

inline GeneratedCustomRange const* FindGeneratedCustomRange(uint32 itemId)
{
    for (GeneratedCustomRange const& range : sGeneratedCustomRanges)
        if (itemId >= range.first && itemId <= range.last)
            return &range;

    return nullptr;
}

#endif // GENERATED_CUSTOM_RANGES_H
